# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  labels:
    app: {{.Chart.Name}}
    prometheus-monitoring: "true"
spec:
  selector:
    app: {{.Chart.Name}}
  ports:
    - name: {{ .Values.ports.http.name }}
      port: {{ .Values.ports.http.value }}
      protocol: TCP
    - name: {{ .Values.ports.management.name }}
      port: {{ .Values.ports.management.value }}
      protocol: TCP