resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1200Mi
probes:
  liveness:
    httpGet:
      path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 12

  readiness:
    httpGet:
      path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 10
  failureThreshold: 6

ports:
  http:
    name: http
    value: 8080
  management:
    name: management
    value: 8081
ingress:
  enabled: true